apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.1
apiServerCertSANs:
- k8s-master01
- k8s-master02
- k8s-master03
- k8s-master-lb
- 192.168.20.20
- 192.168.20.21
- 192.168.20.22
- 192.168.20.10
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.20.21:2379"
      advertise-client-urls: "https://192.168.20.21:2379"
      listen-peer-urls: "https://192.168.20.21:2380"
      initial-advertise-peer-urls: "https://192.168.20.21:2380"
      initial-cluster: "k8s-master01=https://192.168.20.20:2380,k8s-master02=https://192.168.20.21:2380"
      initial-cluster-state: existing
    serverCertSANs:
      - k8s-master02
      - 192.168.20.21
    peerCertSANs:
      - k8s-master02
      - 192.168.20.21
networking:
  # This CIDR is a calico default. Substitute or remove for your CNI provider.
  podSubnet: "172.168.0.0/16"
